/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ai;

import org.example.App;
import static org.testng.Assert.assertNotNull;
import org.testng.annotations.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
